### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#122]
Receive this error run I run this file. Traceback below. File Attached.

> Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\linkrot.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\linkrot\cli.py", line 215, in main
    text = get_text_output(pdf, args)
  File "c:\python38\lib\site-packages\linkrot\cli.py", line 126, in get_text_output
    for k, v in sorted(pdf.get_metadata().items()):
TypeError: '<' not supported between instances of 'NoneType' and 'str
'
[ah-4.pdf](https://github.com/marshalmiller/linkrot/files/9222571/ah-4.pdf)

**Comment by marshalmiller** [comment]
I commented out the metadata section for now. It has solved the issue. But I would still like to display the metadata from he PDF if possible.

**Comment by marshalmiller** [comment]
Resolved in 3.8.5. Thanks to the community at StackOverflow for allowing us to keep this functionality and fixing the bug itself.
