### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 16: character maps to <undefined>

### ISSUE THREAD

**Issue by marshalmiller** [marshalmiller/linkrot#124]
Recieve this error when I run with this file. Traceback below. File Attached.

> Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\linkrot.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\linkrot\cli.py", line 182, in main
    pdf = linkrot.linkrot(args.pdf)
  File "c:\python38\lib\site-packages\linkrot\__init__.py", line 131, in __init__
    self.reader = PDFMinerBackend(self.stream)
  File "c:\python38\lib\site-packages\linkrot\backends.py", line 204, in __init__
    self.metadata[k] = make_compat_str(v)
  File "c:\python38\lib\site-packages\linkrot\backends.py", line 67, in make_compat_str
    out_str = in_str.decode(enc["encoding"])
  File "c:\python38\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 16: character maps to <undefined>

[ah-6.pdf](https://github.com/marshalmiller/linkrot/files/9222597/ah-6.pdf)

**Comment by marshalmiller** [comment]
This is a duplicate of Issue #121. I will close as a result.
